jwt:
  secret: dev-smartbalaram-jwt-secret-key-2025!

spring:
  data:
    mongodb:
      uri: mongodb+srv://b9048635:p1pPLXpUFQGMSSId@cluster0.man4orn.mongodb.net/emiwarning-db?retryWrites=true&w=majority&tls=true
      database: emiwarning-db

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
    voyager:
      enabled: true
      path: /voyager

risk:
  weight-emi-percent: 0.6
  weight-missed-emi: 2.0
  weight-tenure: 0.1
  score-threshold-low: 30
  score-threshold-medium: 60
