server:
  port: 8082

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}   # ✅ Injected via Render env var
      database: emiwarning-db

  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
    voyager:
      enabled: true
      path: /voyager

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:disabled}  # Optional fallback

jwt:
  secret: ${JWT_SECRET}   # ✅ Inject via Render secret environment var

risk:
  weight-emi-percent: 0.6
  weight-missed-emi: 2.0
  weight-tenure: 0.1
  score-threshold-low: 30
  score-threshold-medium: 60
